name: stochsim
version: 0.5.10
summary: System dynamics simulation
description: >
  System dynamics simulation

confinement: strict

parts:
  stochsd:
    plugin: dump
    source: StochSim-Linux64bit-2018-07-29.tgz
    stage-packages:
    - libasound2
    - libatk1.0-0
    - libatk-bridge2.0-0
    - libatspi2.0-0
    - libavahi-client3
    - libavahi-common3
    - libboost-filesystem1.58.0
    - libboost-system1.58.0
    - libcairo2
    - libcairo-gobject2
    - libcomerr2
    - libcups2
    - libdatrie1
    - libdbus-1-3
    - libepoxy0
    - libexpat1
    - libffi6
    - libfontconfig1
    - libfreetype6
    - libgcc1
    - libgcrypt20
    - libgdk-pixbuf2.0-0
    - libgmp10
    - libgnutls30
    - libgpg-error0
    - libgraphite2-3
    - libgssapi-krb5-2
    - libgtk-3-0
    - libharfbuzz0b
    - libhogweed4
    - libidn11
    - libk5crypto3
    - libkeyutils1
    - libkrb5-3
    - libkrb5support0
    - liblzma5
    - libmirclient9
    - libmircommon7
    - libmircore1
    - libmirprotobuf3
    - libnettle6
    - libnss3
    - libp11-kit0
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpcre3
    - libpixman-1-0
    - libpng12-0
    - libprotobuf-lite9v5
    - libselinux1
    - libstdc++6
    - libsystemd0
    - libtasn1-6
    - libthai0
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1-mesa
    - libx11-6
    - libx11-xcb1
    - libxau6
    - libxcb1
    - libxcb-render0
    - libxcb-shm0
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxdmcp6
    - libxext6
    - libxfixes3
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libxrender1
    - libxss1
    - libxtst6
    - zlib1g
    - libgl1-mesa-glx

apps:
  stochsim:
    command: stochsim
    plugs:
    - network
    - network-bind
    - x11
    - wayland
    - desktop
    - opengl
    - pulseaudio
    - browser-support
    - screen-inhibit-control

    
